### ISSUE TITLE
Status is Away

### ISSUE THREAD

**Issue by RLP1369** [nitaybz/homebridge-network-presence#1]
I have installed the plugin via Hoobs.  Nothing appears in HomeKit, but does show in the Eve app.  The device status is always shown as “away”.  I configured my iPhone using Mac and an iPad using IP, both showed “away”
Is there an additional plugin needed?

**Comment by nitaybz** [comment]
It should show in the Home app on the top row of sensors... try to look in the room where your bridge is.

Regarding the discovery... on your iPhone make sure private address is not activated on your current WiFi connection. Private address makes the MAC address on the iPhone change every time you connect into the network, Which is not very good with this plugin looking for that temporary address.

Hope it helps

**Comment by RLP1369** [comment]
Thank you for the rapid response!  I got it worked out after I sent the issue!
One more question, is there a way to configure the threshold in seconds?

Thanks!

**Comment by nitaybz** [comment]
Threshold in seconds has no use... I recommend to set it between 15 to 30 minutes since some phones disappear from the network for that long when their screen is off

On 10 Nov 2020, at 19:52, RLP1369 <notifications@github.com> wrote:

﻿
Thank you for the rapid response! I got it worked out after I sent the issue!
One more question, is there a way to configure the threshold in seconds?

Thanks!

**Comment by RLP1369** [comment]
Ok.  One last question, what is the frequency that the plugin pings the WiFi?  And is that configurable?

**Comment by RLP1369** [comment]
The reason I asked about the ping, the system only maintains my phone as “occupied” for a short period, which defeats the purpose of the plugin.

**Comment by nitaybz** [comment]
it's querying every seconds via arp...
that's why I created the threshold... so it will make sure it's not disconnecting you during this threshold and it's also reset every time you connect or reconnect
