### ISSUE TITLE
Error from HUE-Plugin

### ISSUE THREAD

**Issue by redbull290** [nitaybz/homebridge-network-presence#7]
After I installed the plugin, I received many errors from the HUE plugin in the log file, such as 'Heartbeat XXX, Drift XXX'.
Could that possibly indicate a resource problem? Or is my ping interval set too short at 10 seconds?

**Comment by nitaybz** [comment]
it doesn't sound like an error... can you share some logs?

**Comment by notorioustubze** [comment]
I can confirm I'm getting multiple heartbeat drift warning from the Philips Hue plugin since installing Network presence.
[23/12/2020, 15:18:02] [Hue] heartbeat 1474, drift 280
[23/12/2020, 15:22:45] [Hue] heartbeat 1757, drift 263

**Comment by nitaybz** [comment]
Please test v1.2.0 and report back

**Comment by notorioustubze** [comment]
Thank you for the update I have installed it and will let you know if things improve.

**Comment by notorioustubze** [comment]
Hey, been checking the logs and so far so good whatever you changed appears to be working. So thank you! 😁

**Comment by nitaybz** [comment]
Glad it helped :)
Closing...
